------- Generated by SYS.DBMS_METADATA on 10-Jun-2010 at 13:38:11 -------

  CREATE OR REPLACE TRIGGER "HR"."SUM_SALARY_CHECK" 
 AFTER 
 INSERT OR UPDATE
 ON WORKING_SALARY
 REFERENCING OLD AS OLD NEW AS NEW
declare
e exception;
pragma exception_init (e, -20501);
sum_sal number;
begin
select sum(salary) into sum_sal from working_salary;
if sum_sal > 375000 then
    raise_application_error(-20501,' salary sum exceeded');
end if;
exception
when e then
dbms_output.put_line( SQLERRM);
end;
ALTER TRIGGER "HR"."SUM_SALARY_CHECK" ENABLE
 
/
