------- Generated by SYS.DBMS_METADATA on 10-Jun-2010 at 13:35:49 -------

  CREATE OR REPLACE PROCEDURE "HR"."GETEMPDEP" 


   IS
   cursor c_emp_list (lastname varchar2)  is
    select e.first_name, e.last_name, d.department_name, e.salary  from employees e
    inner join departments d on e.department_id = d.department_id
    where e.last_name <= lastname
    order by e.last_name;
    --order by d.department_id;

    type tr_emp is record (
       v_firstName employees.first_name%TYPE,
       v_lastName employees.last_name%TYPE,
       v_department departments.department_name%TYPE,
       v_salary employees.salary%type
    );
    emp_elem tr_emp;

   type t_emp_table is table of varchar2(32)
       index by varchar2(128);
   dep_emp_table t_emp_table;
   v_index varchar2(128);

   type t_emp_table2 is table of tr_emp
       index by varchar2(128);
   dep_emp_table2 t_emp_table2;
   v_index2 varchar2(128);

   type t_nested_table is table of varchar2(128);
   -- type emp_per_dep_type is table of employees.last_name%type;
   type t_emp_table3 is table of t_nested_table
       index by varchar2(128);
   nested_table3 t_nested_table;
   dep_emp_table3 t_emp_table3;
   v_index3 varchar2(128);


BEGIN
    dbms_output.put_line ('start');
    --dep_emp_table3 := t_emp_table3();
    for r_emp in c_emp_list('Chen') loop
        dep_emp_table (r_emp.first_name  || ' ' || r_emp.last_name) := r_emp.department_name;
        dep_emp_table2 (r_emp.first_name  || ' ' || r_emp.last_name):= r_emp;
        --if dep_emp_table3(r_emp.department_name) is null then
        --   dep_emp_table3(r_emp.department_name) := t_nested_table();
        --end if;
        --nested_table3 := dep_emp_table3(r_emp.department_name);
        --nested_table3.extend;
        --nested_table3(nested_table3.last) := r_emp.first_name  || ' ' || r_emp.last_name;

        dbms_output.put_line (r_emp.first_name  || ' ' ||
                              r_emp.last_name  || ': ' ||
                              r_emp.department_name );
    end loop;

    v_index := dep_emp_table2.first;
    loop
        exit when v_index is null;
        emp_elem := dep_emp_table2(v_index);
        -- es geht auch:   dep_emp_table2(v_index).v_department
        dbms_output.put_line(v_index || '  --  ' || emp_elem.v_department || ' for ' || emp_elem.v_salary );
        v_index := dep_emp_table.next(v_index);
        --if v_index is null then
        --  exit;
        --end if;
    end loop;

    /*  ***
    v_index := dep_emp_table.first;
    loop
        dbms_output.put_line(v_index || '  --  ' || dep_emp_table(v_index));
        v_index := dep_emp_table.next(v_index);
        if v_index is null then
          exit;
        end if;
    end loop;
    *** */


END; -- Procedure
 
/
